// Phase 1-3: 기사 초안 생성기.
// mock 구현(generateMockArticleDraft)과 실제 AI 연동을 위한 인터페이스
// (generateAiArticleDraft)를 분리한다.
//
// generateMockArticleDraft는 prompts/generate-article.prompt.md의 출력 형식
// (title, content, citedSourceIds)을 그대로 따르되, LLM 대신 등록된 출처를
// 템플릿에 채워 넣는다. article.contract.yaml의 min-content-length(500자),
// min-linked-sources(3개) 규칙을 항상 만족하도록 생성한다.
//
// generateAiArticleDraft는 prompts/article-draft.v1.md 기준으로 Phase 1-3 이후
// 실제 LLM 호출로 구현한다.

import { getAnthropicClient, ANTHROPIC_MODEL } from "./anthropic-client";
import type { Source, Theme } from "@/lib/types/domain";
import type { SourceSummary } from "./source-summarizer";

export interface GeneratedArticle {
  title: string;
  content: string;
  citedSourceIds: string[];
}

const MIN_CONTENT_LENGTH = 500;

const FILLER_PARAGRAPH: Record<Theme["language"], string> = {
  ko: "이 기사는 mock article generator에 의해 자동 생성된 초안(draft)입니다. 실제 AI 모델을 통한 생성은 prompts/article-draft.v1.md를 기반으로 연동될 예정이며, 현재는 등록된 출처의 메타데이터를 바탕으로 본문을 구성합니다. 이 초안은 article.contract.yaml의 계약 검사를 통과한 뒤 AI Evals와 사용자 승인 절차를 거쳐야 reviewed 상태로 전환될 수 있습니다.",
  en: "This article is a draft automatically generated by the mock article generator. Generation via a real AI model will be wired up based on prompts/article-draft.v1.md. For now, the body is assembled from the metadata of the registered sources. This draft must pass the article.contract.yaml checks, then AI Evals and human approval before it can be transitioned to the reviewed status.",
};

/**
 * Phase 1-3: 실제 AI API를 호출하지 않는 mock 기사 초안 생성기.
 */
export function generateMockArticleDraft(theme: Theme, sources: Source[]): GeneratedArticle {
  const lang = theme.language;
  const title = theme.title;
  const citedSourceIds = sources.map((source) => source.id);

  const sections =
    lang === "ko"
      ? buildKoreanSections(theme, sources)
      : buildEnglishSections(theme, sources);

  let content = sections.join("\n\n");
  while (content.length < MIN_CONTENT_LENGTH) {
    content += `\n\n${FILLER_PARAGRAPH[lang]}`;
  }

  return { title, content, citedSourceIds };
}

const ARTICLE_SYSTEM_PROMPT = `당신은 블로그/홈페이지 기사를 작성하는 에디터입니다.
아래 제공된 출처 요약(sourceSummaries) 안의 정보만을 근거로 기사를 작성하세요.

규칙:
1. 제목을 포함하여 작성하세요.
2. 본문은 공백 포함 500자 이상이어야 합니다.
3. 제공된 출처 요약 중 최소 3개 이상을 citedSourceIds에 포함하고, 본문에서
   실제로 언급/인용해야 합니다.
4. 출처 요약에 없는 통계, 날짜, 고유명사(인명/기관명/지명 등)를 새로 만들어
   추가하지 마세요 (hallucination 금지).
5. 사실(fact)과 의견(opinion)을 구분해서 서술하세요. 의견은 "~로 보인다",
   "~라는 평가가 있다" 등으로 표현하세요.
6. 클릭베이트성 과장 표현(예: "충격", "경악", "○○가 다 죽었다" 등)을 제목과
   본문에 사용하지 마세요.
7. 기사는 도입 - 본문 - 결론 구조를 가져야 합니다.
8. 출력은 반드시 아래 JSON 형식만 반환하세요. 그 외 텍스트는 출력하지 마세요.

출력 형식:
{
  "title": "기사 제목",
  "content": "기사 본문 (markdown, 500자 이상)",
  "citedSourceIds": ["source-id-1", "source-id-2", "source-id-3"],
  "status": "draft"
}`;

function buildArticleUserPrompt(theme: Theme, sourceSummaries: SourceSummary[]): string {
  const summaryLines = sourceSummaries
    .map((summary) =>
      [
        `- sourceId: ${summary.sourceId}`,
        `  title: ${summary.title}`,
        `  url: ${summary.url}`,
        `  publisher: ${summary.publisher}`,
        `  publishedAt: ${summary.publishedAt}`,
        `  summary: ${summary.summary}`,
      ].join("\n")
    )
    .join("\n");

  return [
    `주제: ${theme.title}`,
    `주제 설명: ${theme.description}`,
    `주요 키워드: ${theme.keywords.join(", ")}`,
    `출력 언어: ${theme.language}`,
    "",
    "출처 요약 목록:",
    summaryLines,
    "",
    "위 출처 요약을 근거로 기사를 작성하세요.",
  ].join("\n");
}

interface RawGeneratedArticle {
  title?: unknown;
  content?: unknown;
  citedSourceIds?: unknown;
}

/**
 * Phase 1-4: prompts/article-draft.v1.md 기준으로 Anthropic API를 호출해
 * 기사 초안을 생성한다. 출처가 3개 미만이면 호출하지 않는다 (호출부에서 검사).
 * JSON parse에 실패하면 에러를 던진다 (호출부에서 mock 초안으로 대체 처리한다).
 * 반환되는 status는 항상 "draft"로 강제한다 (모델 응답값과 무관).
 */
export async function generateAiArticleDraft(
  theme: Theme,
  sourceSummaries: SourceSummary[]
): Promise<GeneratedArticle> {
  const client = getAnthropicClient();

  const response = await client.messages.create({
    model: ANTHROPIC_MODEL,
    max_tokens: 4096,
    system: ARTICLE_SYSTEM_PROMPT,
    messages: [{ role: "user", content: buildArticleUserPrompt(theme, sourceSummaries) }],
  });

  const textBlock = response.content.find((block) => block.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("generateAiArticleDraft: AI 응답에서 텍스트를 찾을 수 없습니다.");
  }

  let parsed: RawGeneratedArticle;
  try {
    parsed = JSON.parse(textBlock.text);
  } catch {
    throw new Error("generateAiArticleDraft: AI 응답을 JSON으로 해석할 수 없습니다.");
  }

  if (typeof parsed.title !== "string" || typeof parsed.content !== "string") {
    throw new Error("generateAiArticleDraft: AI 응답에 title 또는 content가 없습니다.");
  }

  const citedSourceIds = Array.isArray(parsed.citedSourceIds)
    ? parsed.citedSourceIds.filter((id): id is string => typeof id === "string")
    : [];

  return { title: parsed.title, content: parsed.content, citedSourceIds };
}

function buildKoreanSections(theme: Theme, sources: Source[]): string[] {
  const keywordLine =
    theme.keywords.length > 0 ? `주요 키워드: ${theme.keywords.join(", ")}` : "";

  const intro = [
    `# ${theme.title}`,
    "",
    "## 개요",
    theme.description || `${theme.title}에 대한 자동 생성 기사 초안입니다.`,
    keywordLine,
  ]
    .filter(Boolean)
    .join("\n");

  const body = [
    "## 출처별 핵심 내용",
    ...sources.map((source, index) => {
      const meta = [source.publisher, source.publishedAt].filter(Boolean).join(", ");
      return [
        `### ${index + 1}. ${source.title}`,
        source.summary || "(요약 정보가 등록되지 않았습니다.)",
        `- 출처: ${source.url}${meta ? ` (${meta})` : ""}`,
      ].join("\n");
    }),
  ].join("\n\n");

  const conclusion = [
    "## 결론",
    `이상으로 "${theme.title}"에 대해 등록된 ${sources.length}개의 출처를 바탕으로 핵심 내용을 정리했습니다.`,
    "본 초안은 자동 생성된 draft이며, AI 평가와 사용자 검토를 거쳐야 reviewed 상태로 전환됩니다.",
  ].join("\n");

  return [intro, body, conclusion];
}

function buildEnglishSections(theme: Theme, sources: Source[]): string[] {
  const keywordLine =
    theme.keywords.length > 0 ? `Key keywords: ${theme.keywords.join(", ")}` : "";

  const intro = [
    `# ${theme.title}`,
    "",
    "## Overview",
    theme.description || `An automatically generated draft article about ${theme.title}.`,
    keywordLine,
  ]
    .filter(Boolean)
    .join("\n");

  const body = [
    "## Key points by source",
    ...sources.map((source, index) => {
      const meta = [source.publisher, source.publishedAt].filter(Boolean).join(", ");
      return [
        `### ${index + 1}. ${source.title}`,
        source.summary || "(No summary provided.)",
        `- Source: ${source.url}${meta ? ` (${meta})` : ""}`,
      ].join("\n");
    }),
  ].join("\n\n");

  const conclusion = [
    "## Conclusion",
    `This article summarizes ${sources.length} sources registered for "${theme.title}".`,
    "This draft must go through AI evaluation and human review before it can be transitioned to the reviewed status.",
  ].join("\n");

  return [intro, body, conclusion];
}
