// Phase 1-3: 기사 초안 생성기.
// mock 구현(generateMockArticleDraft)과 실제 AI 연동(generateAiArticleDraft)을 분리한다.
// Phase 1-10: article writer는 source summary(전문) 대신 key_points(불릿 사실)만
// 전달받아 synthesis 없이 paraphrase하는 경향을 차단한다.
// Phase 1-11: tool_use로 JSON 출력을 강제한다.
// Phase 2-1: article_mode(general_news / source_based_explainer / monetized_blog) 지원.
// mode 인자를 생략하면 기존과 동일하게 source_based_explainer로 동작해 기존 흐름을 깨지 않는다.
// source_based_explainer 개선: "출처 기반 해설 기사" 모드임을 프롬프트에 명확히 하고,
// thesis를 강한 주장이 아닌 중심 해석으로 재정의했다. sourceUsage 필드로 출처별 역할을
// 확인할 수 있게 했고, 사용 가능한 출처(key_points/summary가 있는 출처)가 3개 미만이면
// 실행 전에 InsufficientSourceMaterialError를 던져 mock 생성으로 안전하게 전환되게 했다.
// general_news/monetized_blog 모드와 두 모드의 프롬프트는 이 개선의 대상이 아니다.

import { getAnthropicClient, ANTHROPIC_MODEL } from "./anthropic-client";
import type { Source, Theme } from "@/lib/types/domain";
import type { SourceSummary } from "./source-summarizer";
import {
  AD_SLOT_MARKERS,
  DEFAULT_ARTICLE_MODE,
  adSlotMarkerComment,
  type AdSlotEntry,
  type ArticleMode,
  type InternalLinkSuggestion,
} from "@/lib/articles/article-modes";

/** source_based_explainer의 sourceUsage에서 각 출처가 맡을 수 있는 역할. */
export type SourceUsageRole = "background" | "data" | "contrast" | "analysis" | "implication" | "watch_point";

/** citedSourceIds 중 하나의 출처가 본문에서 어떤 역할로 쓰였는지 나타낸다. */
export interface SourceUsageEntry {
  sourceId: string;
  usedFor: SourceUsageRole[];
}

export interface GeneratedArticle {
  title: string;
  content: string;
  citedSourceIds: string[];
  /**
   * source_based_explainer 전용 부가 필드. citedSourceIds에 포함된 출처가
   * 본문에서 어떤 역할(background/data/contrast/analysis/implication/
   * watch_point)로 쓰였는지 표시한다. 다른 모드는 undefined다. 품질검사/
   * eval에서 출처 활용 방식을 확인하는 용도이며, 현재는 DB에 저장하지
   * 않는다(저장 구조 변경 없이 결과 객체에만 포함).
   */
  sourceUsage?: SourceUsageEntry[];
  /** monetized_blog 전용 부가 필드 (해당 없는 모드는 undefined) */
  seoTitle?: string;
  metaDescription?: string;
  targetKeyword?: string;
  secondaryKeywords?: string[];
  searchIntent?: string;
  readerPersona?: string;
  adSlots?: AdSlotEntry[];
  internalLinkSuggestions?: InternalLinkSuggestion[];
  monetizationScore?: number;
  policyRiskScore?: number;
}

/**
 * 본문에 AD_SLOT_MARKERS가 모두 존재하는지 확인하고, 빠진 marker는 본문 끝에
 * 추가한다. 실제 AdSense 코드는 절대 삽입하지 않고 HTML 주석 marker만 사용한다.
 */
function ensureAdSlotMarkers(content: string): { content: string; adSlots: AdSlotEntry[] } {
  let result = content;
  const adSlots: AdSlotEntry[] = [];

  for (const position of AD_SLOT_MARKERS) {
    const marker = adSlotMarkerComment(position);
    if (!result.includes(marker)) {
      result += `\n\n${marker}`;
    }
    adSlots.push({ position, marker });
  }

  return { content: result, adSlots };
}

const MIN_CONTENT_LENGTH = 500;

const FILLER_PARAGRAPH: Record<Theme["language"], string> = {
  ko: "이 기사는 mock article generator에 의해 자동 생성된 초안(draft)입니다. 실제 AI 모델을 통한 생성은 prompts/article-draft.v1.md를 기반으로 연동될 예정이며, 현재는 등록된 출처의 메타데이터를 바탕으로 본문을 구성합니다. 이 초안은 article.contract.yaml의 계약 검사를 통과한 뒤 AI Evals와 사용자 승인 절차를 거쳐야 reviewed 상태로 전환될 수 있습니다.",
  en: "This article is a draft automatically generated by the mock article generator. Generation via a real AI model will be wired up based on prompts/article-draft.v1.md. For now, the body is assembled from the metadata of the registered sources. This draft must pass the article.contract.yaml checks, then AI Evals and human approval before it can be transitioned to the reviewed status.",
};

/**
 * Phase 1-3: 실제 AI API를 호출하지 않는 mock 기사 초안 생성기.
 * Phase 2-1: mode를 생략하면 기존과 동일하게 source_based_explainer로 동작한다
 * (기존 흐름 보존).
 */
export function generateMockArticleDraft(
  theme: Theme,
  sources: Source[],
  mode: ArticleMode = DEFAULT_ARTICLE_MODE
): GeneratedArticle {
  if (mode === "general_news") {
    return generateGeneralNewsMock(theme, sources);
  }
  if (mode === "monetized_blog") {
    return generateMonetizedBlogMock(theme, sources);
  }
  return generateSourceBasedExplainerMock(theme, sources);
}

function generateSourceBasedExplainerMock(theme: Theme, sources: Source[]): GeneratedArticle {
  const lang = theme.language;
  const title = theme.title;
  const citedSourceIds = sources.map((source) => source.id);

  const sections =
    lang === "ko"
      ? buildKoreanSections(theme, sources)
      : buildEnglishSections(theme, sources);

  let content = sections.join("\n\n");
  while (content.length < MIN_CONTENT_LENGTH) {
    content += `\n\n${FILLER_PARAGRAPH[lang]}`;
  }

  return { title, content, citedSourceIds };
}

/** Phase 2-1: 일반 기사형(general_news) mock 생성기 — 짧고 간결한 구조. */
function generateGeneralNewsMock(theme: Theme, sources: Source[]): GeneratedArticle {
  const title = theme.title;
  const citedSourceIds = sources.map((source) => source.id);
  const desc = theme.description || `${theme.title}에 대한 최신 소식`;

  const issueParts = sources.slice(0, 3).map((s) => {
    const point = s.keyPoints?.[0] || s.summary?.substring(0, 80) || "(내용 없음)";
    return `- **${s.title || s.url}**: ${point}`;
  });

  const sections = [
    `# ${title}`,
    ["## 리드문", `${desc} 관련 출처 ${sources.length}건을 바탕으로 핵심 사실을 빠르게 전달한다.`].join("\n"),
    ["## 핵심 내용", ...issueParts].join("\n"),
    ["## 배경", `"${title}"는 최근 발생한 이슈다. 등록된 출처를 바탕으로 사실관계를 정리했다.`].join("\n"),
    [
      "## 관련 자료 또는 반응",
      sources.length > 0
        ? "등록된 출처들이 전하는 관련 사실과 반응은 다음과 같다."
        : "등록된 관련 자료가 아직 없다.",
    ].join("\n"),
    [
      "## 향후 전망",
      "추가 사실 확인과 후속 보도에 따라 상황이 달라질 수 있다.",
      "",
      "> ⚠️ 이 초안은 mock article generator가 자동 생성한 draft입니다.",
    ].join("\n"),
    [
      "## 참고 출처",
      ...sources.map((s, i) => `${i + 1}. ${s.title || s.url} ${s.publisher ? `(${s.publisher})` : ""}`),
    ].join("\n"),
  ];

  let content = sections.join("\n\n");
  while (content.length < MIN_CONTENT_LENGTH) {
    content += `\n\n${FILLER_PARAGRAPH[theme.language]}`;
  }

  return { title, content, citedSourceIds };
}

/** Phase 2-1: 수익형 블로그형(monetized_blog) mock 생성기 — SEO/광고 슬롯/체크리스트 포함. */
function generateMonetizedBlogMock(theme: Theme, sources: Source[]): GeneratedArticle {
  const title = theme.title;
  const citedSourceIds = sources.map((source) => source.id);
  const keywordStr = theme.keywords.join(", ");
  const targetKeyword = theme.keywords[0] || theme.title;
  const seoTitle = `${title} 완벽 가이드 (${new Date().getFullYear()}년 기준)`;
  const metaDescription = `${title}에 대해 알아야 할 핵심 정보를 정리했다. ${keywordStr}`.slice(0, 160);

  const sections = [
    `# ${seoTitle}`,
    ["## 도입부", `${theme.description || title}에 대해 궁금한 점을 이 글에서 모두 정리했다.`].join("\n"),
    adSlotMarkerComment("after_intro"),
    ["## 핵심 요약", `- ${title} 관련 핵심 정보 ${sources.length}건을 정리했다.`].join("\n"),
    adSlotMarkerComment("after_summary"),
    ["## 목차", "1. 문제 설명", "2. 핵심 정보", "3. 비교", "4. 체크리스트", "5. 주의점", "6. FAQ", "7. 결론"].join("\n"),
    ["## 문제 설명", `"${title}"를 찾는 독자가 흔히 겪는 어려움을 정리했다.`].join("\n"),
    [
      "## 핵심 정보",
      ...sources.slice(0, 3).map((s) => `- **${s.title || s.url}**: ${s.keyPoints?.[0] || s.summary?.substring(0, 80) || "(내용 없음)"}`),
    ].join("\n"),
    adSlotMarkerComment("mid_content_1"),
    ["## 비교표", "| 항목 | 설명 |", "|---|---|", `| ${title} | 출처 ${sources.length}건 기반 요약 |`].join("\n"),
    adSlotMarkerComment("mid_content_2"),
    ["## 체크리스트", "- [ ] 출처를 확인했는가", "- [ ] 최신 정보인가", "- [ ] 나에게 해당하는 정보인가"].join("\n"),
    ["## 주의점", "이 글은 일반 정보 제공 목적이며, 개별 상황에 따라 다를 수 있다."].join("\n"),
    adSlotMarkerComment("before_faq"),
    [
      "## FAQ",
      `**Q. ${title}란 무엇인가?**`,
      "A. 등록된 출처를 바탕으로 정리한 정보다.",
    ].join("\n"),
    adSlotMarkerComment("before_conclusion"),
    ["## 결론", `"${title}"에 대해 핵심 내용을 정리했다. 추가 정보는 참고자료를 확인하라.`].join("\n"),
    [
      "## 관련 글 추천",
      `- ${title} 관련 주제를 더 깊이 다루는 글 (추후 연결 예정)`,
    ].join("\n"),
    [
      "## 참고자료",
      ...sources.map((s, i) => `${i + 1}. ${s.title || s.url} ${s.publisher ? `(${s.publisher})` : ""}`),
    ].join("\n"),
  ];

  let content = sections.join("\n\n");
  while (content.length < MIN_CONTENT_LENGTH) {
    content += `\n\n${FILLER_PARAGRAPH[theme.language]}`;
  }

  const { content: contentWithAllSlots, adSlots } = ensureAdSlotMarkers(content);

  const internalLinkSuggestions: InternalLinkSuggestion[] = [
    { title: `${title} 관련 주제 1`, reason: "동일 카테고리 독자 관심사" },
  ];

  return {
    title,
    content: contentWithAllSlots,
    citedSourceIds,
    seoTitle,
    metaDescription,
    targetKeyword,
    secondaryKeywords: theme.keywords.slice(1),
    searchIntent: "informational",
    readerPersona: `${title}에 관심 있는 일반 독자`,
    adSlots,
    internalLinkSuggestions,
    monetizationScore: 50,
    policyRiskScore: 10,
  };
}

// ─────────────────────────────────────────────────────────────
// AI 기사 생성 (tool_use 방식)
// ─────────────────────────────────────────────────────────────

const ARTICLE_SYSTEM_PROMPT = `당신은 15년 경력의 전문 저널리스트이며, 여러 출처의 사실 조각을 종합해
일반 독자가 이해할 수 있는 "출처 기반 해설 기사"를 작성합니다.

이 모드(source_based_explainer)는 단순 뉴스 요약이나 SEO 블로그
글쓰기가 아닙니다. 광고 클릭을 유도하는 문구나 수익형 블로그 문체를
사용하지 않으며, 출처들이 공통으로 보여주는 흐름과 차이를 바탕으로
하나의 중심 해석을 제시하는 해설 기사 작성 모드입니다.

목표는 출처를 이어 붙이는 것이 아니라, 출처들 사이의 공통점·차이점·
긴장관계를 종합해 독자가 "왜 이 주제가 중요한지"를 이해하도록 돕는
것입니다.

【작업 순서 — 반드시 이 순서를 지킬 것】
1. synthesis_notes 작성 (내부 분석 메모, 독자에게 노출되지 않음):
   - 모든 출처의 key_points를 훑은 뒤, 공통 논지·의미 있는 차이점·
     긴장관계·독자에게 중요한 이유를 3~5문장으로 정리한다.
   - 특정 출처 하나의 구조를 따라가지 말고, 여러 출처를 재배열·통합해
     해석한다.
   - 출처에 없는 수치, 날짜, 고유명사, 인과관계는 만들지 않는다.
2. thesis 작성:
   - 강한 주장이나 사설식 결론이 아니라, "이 사안을 이해하는 중심
     해석"이다.
   - 출처들이 보여주는 흐름과 의미를 1~2문장으로 압축한다.
   - 찬반을 과도하게 단정하지 않는다.
   - 이후 title과 content는 이 thesis를 중심으로 구성한다.
3. title 작성:
   - thesis의 핵심을 반영한다 (40자 이내).
   - "충격", "대박", "난리", "무조건", "끝났다" 같은 클릭베이트 표현을
     금지한다.
   - 출처에 없는 숫자나 고유명사를 제목에 넣지 않는다.
   - 결론을 과도하게 단정하지 않는다.
4. content 작성:
   - thesis를 중심으로, 아래 "content가 포함해야 할 7가지 기능"을
     포함한 기사를 작성한다.
   - 800자 이상을 권장하며(최소 500자), markdown으로 작성한다.
5. sourceUsage 작성:
   - citedSourceIds에 포함된 각 출처가 본문에서 어떤 역할로 쓰였는지
     표시한다 (아래 "sourceUsage" 항목 참고).

【문체 기준】
- 한국 주요 일간지 수준의 품격 있는 설명형 저널리즘
- 역피라미드 구조 + 내러티브 흐름
- 각 문단은 하나의 생각을 담고 다음 문단으로 자연스럽게 이어진다
- 독자가 기사를 다 읽고 나서 "아, 이래서 이 주제가 중요하구나"를 느껴야 한다

【절대 금지】
- key_points 항목을 그대로 복사하거나 단어 순서만 바꾸는 paraphrase
- 출처를 순서대로 나열하는 구조 ("A 기사에 따르면... B 기사에 따르면... C 기사에 따르면..." 패턴)
- 특정 출처 하나의 문단 순서·논리 전개를 그대로 따라가는 source structure copy
- key_points에 없는 수치·날짜·고유명사를 만들어 추가하는 것 (hallucination)
- 출처에 없는 인과관계를 단정하는 것
- 출처에 없는 전망을 단정하는 것
- 광고 클릭 유도 표현, 수익형 블로그 문체
- 선정적 제목, 과장된 위기감
- 개인 투자·의료·법률 판단을 단정하는 표현
- 결론에서 근거 없이 "~일 것이다", "~해야 한다"를 나열하는 빈약한 전망
- 500자 미만 본문

【불확실성 표현 규칙】
- 출처에서 직접 확인되지 않는 인과관계, 전망, 평가는 단정하지 않는다.
- 필요한 경우 "가능성이 있다", "관찰된다", "해석할 수 있다", "과제로
  남는다"처럼 제한적으로 표현한다.
- 다만 출처가 직접 확인한 사실은 명확하게 쓴다 (불필요하게 모든
  문장을 헤지하지 않는다).

【content가 포함해야 할 7가지 기능 — heading을 기계적으로 고정하지 않는다】
아래는 content가 반드시 포함해야 할 기능이다. 다만 실제 heading은
주제에 맞게 자연스럽게 작성하고, 모든 기사에서 "## 배경", "## 핵심
쟁점" 같은 고정 제목을 기계적으로 반복하지 않아도 된다 — 기능이
드러나면 충분하다.
1. 리드문 — 독자가 계속 읽을 이유를 제시 (thesis 반영)
2. 배경 — 이 주제가 왜 지금 중요한지 맥락
3. 핵심 쟁점 — 여러 출처가 공통으로 짚는 문제의 핵심
4. 다각도 분석 — 출처들의 공통점·차이점·긴장관계를 통합해 해석
5. 사실과 데이터 — 출처에 명시된 구체적 사실·수치·사례만 사용
6. 독자에게 주는 의미 — 이 정보가 독자에게 왜 중요한지 해석
7. 향후 전망 또는 과제 — 출처 기반의 제한적 전망 또는 아직 해결되지
   않은 과제

【sourceUsage】
citedSourceIds에 포함된 각 sourceId가 본문에서 어떤 역할로 쓰였는지
표시한다. 하나의 sourceId가 여러 역할을 겸할 수 있다.
- background: 배경 설명에 사용
- data: 구체적 사실·수치·데이터 제공
- contrast: 다른 출처와의 차이·긴장관계를 보여주는 데 사용
- analysis: 다각도 분석에 사용
- implication: 독자에게 주는 의미 해석에 사용
- watch_point: 향후 전망/과제 제시에 사용
citedSourceIds에 없는 sourceId는 sourceUsage에 포함하지 않는다.`;

const ARTICLE_TOOL = {
  name: "write_article",
  description:
    "기사 작성 결과를 저장한다. synthesis_notes → thesis → title → content → sourceUsage 순서로 반드시 작성해야 한다.",
  input_schema: {
    type: "object" as const,
    properties: {
      synthesis_notes: {
        type: "string",
        description: "출처 분석 메모 (독자에게 노출되지 않음). 출처들의 공통 논지·차이점·긴장관계·의미를 3~5문장으로 정리.",
      },
      thesis: {
        type: "string",
        description:
          "이 기사의 핵심 주장이 아니라 중심 해석 (1~2문장). 강한 단정이나 사설식 결론이 아니어야 하며, content 전체가 이 해석을 뒷받침해야 한다.",
      },
      title: {
        type: "string",
        description: "기사 제목 (40자 이내, thesis 반영, 클릭베이트/출처에 없는 숫자·고유명사 금지)",
      },
      content: {
        type: "string",
        description:
          "기사 본문 (markdown, 공백 포함 800자 이상 권장·최소 500자). 7가지 기능을 포함하되 heading은 자연스럽게 작성한다.",
      },
      citedSourceIds: {
        type: "array",
        items: { type: "string" },
        description: "본문에서 실제로 활용한 출처 ID 목록 (최소 3개)",
      },
      sourceUsage: {
        type: "array",
        description:
          "citedSourceIds에 포함된 sourceId가 본문에서 어떤 역할로 쓰였는지 표시하는 목록. citedSourceIds에 없는 sourceId는 포함하지 않는다.",
        items: {
          type: "object",
          properties: {
            sourceId: { type: "string", description: "citedSourceIds 중 하나와 정확히 일치하는 값" },
            usedFor: {
              type: "array",
              items: {
                type: "string",
                enum: ["background", "data", "contrast", "analysis", "implication", "watch_point"],
              },
              description: "이 출처가 본문에서 수행한 역할 (복수 선택 가능)",
            },
          },
          required: ["sourceId", "usedFor"],
        },
      },
    },
    required: ["synthesis_notes", "thesis", "title", "content", "citedSourceIds", "sourceUsage"],
  },
};

/**
 * article writer에 보낼 출처 입력을 구성한다.
 * summary 전문 대신 key_points(불릿 사실)만 전달해 paraphrase를 차단한다.
 * key_points가 없는 출처는 summary 앞 150자를 짧게 fallback한다.
 */
function buildSourceBlock(summary: SourceSummary): string {
  const lines = [
    `[출처 ${summary.sourceId}]`,
    // sourceUsage.sourceId가 이 값과 정확히 일치해야 하므로, 모델이 ID를
    // 혼동하지 않도록 별도 줄로 한 번 더 명시한다.
    `sourceId(정확히 그대로 사용): ${summary.sourceId}`,
    `제목: ${summary.title}`,
    `출판사: ${summary.publisher || "(없음)"}`,
    `발행일: ${summary.publishedAt || "(없음)"}`,
  ];

  if (summary.sourceAngle) {
    lines.push(`관점: ${summary.sourceAngle}`);
  }

  if (summary.keyPoints.length > 0) {
    lines.push("핵심 사실:");
    summary.keyPoints.forEach((kp) => lines.push(`  • ${kp}`));
  } else if (summary.summary) {
    // key_points가 없는 구형 출처는 summary 150자로 fallback
    const fallback = summary.summary.length > 150
      ? `${summary.summary.substring(0, 150)}…`
      : summary.summary;
    lines.push(`핵심 내용 (요약): ${fallback}`);
  }

  return lines.join("\n");
}

function buildArticleUserPrompt(theme: Theme, sourceSummaries: SourceSummary[]): string {
  const sourceBlocks = sourceSummaries.map(buildSourceBlock).join("\n\n");

  const audienceNote =
    theme.language === "en" ? "General blog readers" : "일반 블로그 독자 (한국어)";

  return [
    `주제: ${theme.title}`,
    `주제 설명: ${theme.description || "(없음)"}`,
    `주요 키워드: ${theme.keywords.join(", ") || "(없음)"}`,
    `독자 대상: ${audienceNote}`,
    "",
    "─── 출처별 핵심 사실 목록 (요약문이 아닌 사실 추출물) ───",
    sourceBlocks,
    "",
    "─── 작업 지시 ───",
    "위 사실 목록을 바탕으로 write_article 도구를 호출하세요.",
    "반드시 synthesis_notes → thesis → title → content → sourceUsage 순서로 채우세요.",
    "각 출처를 순서대로 소개하는 방식으로 작성하지 마세요.",
    "출처의 핵심 사실을 종합·해석하여 하나의 논지가 있는 기사로 작성하세요.",
    "sourceUsage의 sourceId는 위 [출처 ...] 블록의 sourceId와 정확히 동일한 문자열을 사용하세요.",
  ].join("\n");
}

// ─────────────────────────────────────────────────────────────
// source_based_explainer 실행 조건(guard) + sourceUsage 파싱
// ─────────────────────────────────────────────────────────────

/** source_based_explainer가 실제로 종합할 수 있는 최소 출처 개수. */
export const MIN_USABLE_SOURCES_FOR_EXPLAINER = 3;

export interface SourceReadinessCheck {
  ready: boolean;
  usableCount: number;
  totalCount: number;
  message: string;
}

/**
 * key_points와 summary가 모두 비어 있는 출처는 종합(synthesis)할 사실이
 * 없으므로 "사용 가능한 출처"로 세지 않는다.
 */
function isUsableSourceSummary(summary: SourceSummary): boolean {
  return summary.keyPoints.length > 0 || summary.summary.trim().length > 0;
}

/**
 * source_based_explainer 실행 가능 여부를 판단한다. AI 호출 전에 서버
 * 액션/UI에서 미리 확인해 "최소 3개 출처가 필요합니다" 같은 안내를
 * 보여주는 데 사용할 수 있다.
 */
export function checkSourceBasedExplainerReadiness(sourceSummaries: SourceSummary[]): SourceReadinessCheck {
  const usableCount = sourceSummaries.filter(isUsableSourceSummary).length;
  const ready = usableCount >= MIN_USABLE_SOURCES_FOR_EXPLAINER;

  return {
    ready,
    usableCount,
    totalCount: sourceSummaries.length,
    message: ready
      ? `사용 가능한 출처 ${usableCount}건으로 source_based_explainer 모드를 실행할 수 있습니다.`
      : `source_based_explainer는 최소 ${MIN_USABLE_SOURCES_FOR_EXPLAINER}개 이상의 사용 가능한 출처(key_points 또는 summary가 있는 출처)가 필요합니다 ` +
        `(현재 사용 가능: ${usableCount}건, 전체 등록: ${sourceSummaries.length}건). ` +
        "출처를 보강하거나 general_news 모드를 사용하세요.",
  };
}

/**
 * source_based_explainer 실행에 필요한 최소 출처 재료가 부족할 때 던지는
 * 오류. 새 fallback 모드를 만드는 대신, 호출자가 이 오류를 잡아 기존
 * mock 생성 경로로 안전하게 전환할 수 있도록 명확한 상태를 제공한다.
 */
export class InsufficientSourceMaterialError extends Error {
  readonly usableCount: number;
  readonly totalCount: number;

  constructor(check: SourceReadinessCheck) {
    super(check.message);
    this.name = "InsufficientSourceMaterialError";
    this.usableCount = check.usableCount;
    this.totalCount = check.totalCount;
  }
}

const SOURCE_USAGE_ROLES: readonly SourceUsageRole[] = [
  "background",
  "data",
  "contrast",
  "analysis",
  "implication",
  "watch_point",
];

function isSourceUsageRole(value: unknown): value is SourceUsageRole {
  return typeof value === "string" && (SOURCE_USAGE_ROLES as readonly string[]).includes(value);
}

/**
 * AI 응답의 sourceUsage를 검증한다. citedSourceIds에 없는 sourceId나
 * 허용되지 않은 usedFor 값은 조용히 버리고, 그 외 결과는 그대로
 * 반환한다 (형식이 다소 어긋나도 기사 생성 자체를 막지 않는다).
 */
function parseSourceUsage(raw: unknown, citedSourceIds: string[]): SourceUsageEntry[] {
  if (!Array.isArray(raw)) return [];
  const citedSet = new Set(citedSourceIds);
  const result: SourceUsageEntry[] = [];

  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const record = item as Record<string, unknown>;
    const sourceId = typeof record.sourceId === "string" ? record.sourceId : "";
    if (!sourceId || !citedSet.has(sourceId)) continue;

    const usedForRaw = Array.isArray(record.usedFor) ? record.usedFor : [];
    const usedFor = usedForRaw.filter(isSourceUsageRole);
    if (usedFor.length === 0) continue;

    result.push({ sourceId, usedFor });
  }

  return result;
}

/**
 * Phase 1-4: prompts/article-draft.v1.md 기준으로 Anthropic API를 호출해
 * 기사 초안을 생성한다. tool_use로 JSON 출력을 강제한다.
 * 반환되는 status는 항상 "draft"로 강제한다 (모델 응답값과 무관).
 * Phase 2-1: mode를 생략하면 기존과 동일하게 source_based_explainer로 동작한다
 * (기존 흐름 보존 — client 생성 실패 시 즉시 예외, 이하 로직 동일).
 */
export async function generateAiArticleDraft(
  theme: Theme,
  sourceSummaries: SourceSummary[],
  mode: ArticleMode = DEFAULT_ARTICLE_MODE
): Promise<GeneratedArticle> {
  const client = getAnthropicClient();

  if (mode === "general_news") {
    return generateGeneralNewsAiDraft(client, theme, sourceSummaries);
  }
  if (mode === "monetized_blog") {
    return generateMonetizedBlogAiDraft(client, theme, sourceSummaries);
  }
  return generateSourceBasedExplainerAiDraft(client, theme, sourceSummaries);
}

type AnthropicClient = ReturnType<typeof getAnthropicClient>;

async function generateSourceBasedExplainerAiDraft(
  client: AnthropicClient,
  theme: Theme,
  sourceSummaries: SourceSummary[]
): Promise<GeneratedArticle> {
  const readiness = checkSourceBasedExplainerReadiness(sourceSummaries);
  if (!readiness.ready) {
    throw new InsufficientSourceMaterialError(readiness);
  }

  const response = await client.messages.create({
    model: ANTHROPIC_MODEL,
    max_tokens: 8192,
    system: ARTICLE_SYSTEM_PROMPT,
    tools: [ARTICLE_TOOL],
    tool_choice: { type: "tool", name: "write_article" },
    messages: [{ role: "user", content: buildArticleUserPrompt(theme, sourceSummaries) }],
  });

  const toolUseBlock = response.content.find((block) => block.type === "tool_use");
  if (!toolUseBlock || toolUseBlock.type !== "tool_use") {
    throw new Error("generateAiArticleDraft: AI가 도구를 호출하지 않았습니다.");
  }

  const input = toolUseBlock.input as Record<string, unknown>;

  const title = typeof input.title === "string" ? input.title.trim() : "";
  const content = typeof input.content === "string" ? input.content.trim() : "";

  if (!title || !content) {
    throw new Error("generateAiArticleDraft: AI 응답에 title 또는 content가 없습니다.");
  }

  const citedSourceIds = Array.isArray(input.citedSourceIds)
    ? input.citedSourceIds.filter((id): id is string => typeof id === "string")
    : [];

  const sourceUsage = parseSourceUsage(input.sourceUsage, citedSourceIds);

  return { title, content, citedSourceIds, sourceUsage };
}

// ─────────────────────────────────────────────────────────────
// Phase 2-1: 일반 기사형(general_news) AI 생성
// ─────────────────────────────────────────────────────────────

const GENERAL_NEWS_SYSTEM_PROMPT = `당신은 통신사 소속의 스트레이트 뉴스 기자입니다.
빠른 이슈 전달을 목표로, 객관적이고 간결한 일반 기사형 초안을 작성합니다.

【절대 금지】
- 과장된 표현, 클릭베이트성 제목
- 출처에 없는 단정적 주장이나 수치·고유명사 추가 (hallucination)
- 출처를 순서대로 나열하는 구조 ("A 기사에 따르면... B 기사에 따르면...")

【7개 섹션 구조】
1. 리드문 — 무엇이·언제·왜 일어났는지 2~3문장 요약
2. 핵심 내용 — 이슈의 핵심 사실
3. 배경 — 이슈가 발생한 맥락
4. 관련 자료 또는 반응 — 출처가 전하는 관련 사실/반응
5. 향후 전망 — 출처 근거가 있는 전망 (과도한 예측 금지)
6. 참고 출처 — 인용된 출처

빠른 전달이 목적이므로 출처 기반 설명형보다 짧고 간결하게 작성하세요 (500자 이상, 1500자 이내 권장).`;

const GENERAL_NEWS_TOOL = {
  name: "write_general_news_article",
  description: "일반 기사형(general_news) 결과를 저장한다.",
  input_schema: {
    type: "object" as const,
    properties: {
      title: { type: "string", description: "기사 제목 (과장 금지, 40자 이내)" },
      content: { type: "string", description: "기사 본문 (markdown, 500자 이상, 7개 섹션)" },
      citedSourceIds: {
        type: "array",
        items: { type: "string" },
        description: "본문에서 실제로 활용한 출처 ID 목록 (최소 3개)",
      },
    },
    required: ["title", "content", "citedSourceIds"],
  },
};

async function generateGeneralNewsAiDraft(
  client: AnthropicClient,
  theme: Theme,
  sourceSummaries: SourceSummary[]
): Promise<GeneratedArticle> {
  const response = await client.messages.create({
    model: ANTHROPIC_MODEL,
    max_tokens: 4096,
    system: GENERAL_NEWS_SYSTEM_PROMPT,
    tools: [GENERAL_NEWS_TOOL],
    tool_choice: { type: "tool", name: "write_general_news_article" },
    messages: [{ role: "user", content: buildArticleUserPrompt(theme, sourceSummaries) }],
  });

  const toolUseBlock = response.content.find((block) => block.type === "tool_use");
  if (!toolUseBlock || toolUseBlock.type !== "tool_use") {
    throw new Error("generateAiArticleDraft: AI가 도구를 호출하지 않았습니다.");
  }

  const input = toolUseBlock.input as Record<string, unknown>;
  const title = typeof input.title === "string" ? input.title.trim() : "";
  const content = typeof input.content === "string" ? input.content.trim() : "";

  if (!title || !content) {
    throw new Error("generateAiArticleDraft: AI 응답에 title 또는 content가 없습니다.");
  }

  const citedSourceIds = Array.isArray(input.citedSourceIds)
    ? input.citedSourceIds.filter((id): id is string => typeof id === "string")
    : [];

  return { title, content, citedSourceIds };
}

// ─────────────────────────────────────────────────────────────
// Phase 2-1: 수익형 블로그형(monetized_blog) AI 생성
// ─────────────────────────────────────────────────────────────

const MONETIZED_BLOG_SYSTEM_PROMPT = `당신은 검색 유입과 체류시간을 고려하는 SEO 콘텐츠 전문 작가입니다.
독자의 문제 해결을 최우선으로 하는 수익형 블로그 글을 작성합니다.

【절대 금지】
- 과장된 클릭베이트, 허위 또는 과장된 수익 약속
- AdSense 정책을 위반할 수 있는 광고 클릭 유도 문구
- 의료/금융/법률 등 고위험 주제에 대한 단정적 조언
- 출처 없는 주장, 원문 15단어 이상 연속 복사

【실제 광고 코드 절대 금지】
- 실제 AdSense 스크립트나 광고 코드를 절대 작성하지 마세요.
- 광고 위치는 반드시 HTML 주석 marker만 사용하세요: <!-- AD_SLOT: after_summary --> 형태.
- 사용 가능한 marker: after_summary, after_intro, mid_content_1, mid_content_2, before_faq, before_conclusion

【구조】
SEO 제목 → 메타 설명 → 도입부 → 핵심 요약 박스(AD_SLOT: after_summary) → 목차 → 문제 설명 →
핵심 정보(AD_SLOT: mid_content_1) → 비교표(AD_SLOT: mid_content_2) → 체크리스트 → 주의점 →
FAQ(AD_SLOT: before_faq) → 결론(AD_SLOT: before_conclusion) → 관련 글 추천 → 참고자료

monetizationScore(0~100)는 검색 수요, 문제 해결성, 비교/구매 의도, 콘텐츠 확장성, 광고 적합성,
장기 검색 가능성, 경쟁 강도, 정책 위험도를 종합해 산출하세요.
policyRiskScore(0~100, 높을수록 위험)는 허위/과장 수익 약속, 광고 클릭 유도 문구, 선정적 제목,
고위험 단정, 출처 없는 주장, 복사/저작권 위험을 종합해 산출하세요.`;

const MONETIZED_BLOG_TOOL = {
  name: "write_monetized_blog_article",
  description: "수익형 블로그형(monetized_blog) 결과를 저장한다.",
  input_schema: {
    type: "object" as const,
    properties: {
      seoTitle: { type: "string", description: "SEO 제목 (60자 이내, 타깃 키워드 포함)" },
      metaDescription: { type: "string", description: "메타 설명 (160자 이내)" },
      targetKeyword: { type: "string", description: "타깃 키워드" },
      secondaryKeywords: { type: "array", items: { type: "string" }, description: "보조 키워드 목록" },
      searchIntent: { type: "string", description: "검색 의도 (informational/commercial/transactional 등)" },
      readerPersona: { type: "string", description: "독자 페르소나 설명" },
      title: { type: "string", description: "본문에 표시할 제목" },
      content: {
        type: "string",
        description: "기사 본문 (markdown, AD_SLOT marker 포함, 목차/비교표/체크리스트/FAQ 포함, 1200자 이상)",
      },
      citedSourceIds: {
        type: "array",
        items: { type: "string" },
        description: "본문에서 실제로 활용한 출처 ID 목록 (최소 3개)",
      },
      adSlots: {
        type: "array",
        items: {
          type: "object",
          properties: {
            position: { type: "string" },
            marker: { type: "string" },
          },
        },
        description: "본문에 삽입한 AD_SLOT marker 목록",
      },
      internalLinkSuggestions: {
        type: "array",
        items: {
          type: "object",
          properties: {
            title: { type: "string" },
            reason: { type: "string" },
          },
        },
        description: "관련 글 추천 목록",
      },
      monetizationScore: { type: "number", description: "수익화 적합도 점수 (0~100)" },
      policyRiskScore: { type: "number", description: "AdSense 정책 위험도 점수 (0~100, 높을수록 위험)" },
    },
    required: [
      "seoTitle",
      "metaDescription",
      "targetKeyword",
      "title",
      "content",
      "citedSourceIds",
      "monetizationScore",
      "policyRiskScore",
    ],
  },
};

async function generateMonetizedBlogAiDraft(
  client: AnthropicClient,
  theme: Theme,
  sourceSummaries: SourceSummary[]
): Promise<GeneratedArticle> {
  const response = await client.messages.create({
    model: ANTHROPIC_MODEL,
    max_tokens: 8192,
    system: MONETIZED_BLOG_SYSTEM_PROMPT,
    tools: [MONETIZED_BLOG_TOOL],
    tool_choice: { type: "tool", name: "write_monetized_blog_article" },
    messages: [{ role: "user", content: buildArticleUserPrompt(theme, sourceSummaries) }],
  });

  const toolUseBlock = response.content.find((block) => block.type === "tool_use");
  if (!toolUseBlock || toolUseBlock.type !== "tool_use") {
    throw new Error("generateAiArticleDraft: AI가 도구를 호출하지 않았습니다.");
  }

  const input = toolUseBlock.input as Record<string, unknown>;
  const title = typeof input.title === "string" ? input.title.trim() : "";
  let content = typeof input.content === "string" ? input.content.trim() : "";

  if (!title || !content) {
    throw new Error("generateAiArticleDraft: AI 응답에 title 또는 content가 없습니다.");
  }

  const citedSourceIds = Array.isArray(input.citedSourceIds)
    ? input.citedSourceIds.filter((id): id is string => typeof id === "string")
    : [];

  const { content: contentWithAllSlots, adSlots } = ensureAdSlotMarkers(content);
  content = contentWithAllSlots;

  const internalLinkSuggestions: InternalLinkSuggestion[] = Array.isArray(input.internalLinkSuggestions)
    ? input.internalLinkSuggestions
        .filter((item): item is Record<string, unknown> => typeof item === "object" && item !== null)
        .map((item) => ({
          title: typeof item.title === "string" ? item.title : "",
          reason: typeof item.reason === "string" ? item.reason : "",
        }))
    : [];

  const clampScore = (value: unknown): number => {
    const num = typeof value === "number" ? value : 0;
    return Math.max(0, Math.min(100, Math.round(num)));
  };

  return {
    title,
    content,
    citedSourceIds,
    seoTitle: typeof input.seoTitle === "string" ? input.seoTitle : title,
    metaDescription: typeof input.metaDescription === "string" ? input.metaDescription : "",
    // AI가 targetKeyword를 누락하거나 빈 문자열로 응답해도 완전히 비지 않도록
    // theme 키워드/제목으로 fallback한다 (target_keyword 누락 방지).
    targetKeyword:
      typeof input.targetKeyword === "string" && input.targetKeyword.trim()
        ? input.targetKeyword
        : theme.keywords[0] || theme.title,
    secondaryKeywords: Array.isArray(input.secondaryKeywords)
      ? input.secondaryKeywords.filter((k): k is string => typeof k === "string")
      : [],
    searchIntent: typeof input.searchIntent === "string" ? input.searchIntent : "",
    readerPersona: typeof input.readerPersona === "string" ? input.readerPersona : "",
    adSlots,
    internalLinkSuggestions,
    monetizationScore: clampScore(input.monetizationScore),
    policyRiskScore: clampScore(input.policyRiskScore),
  };
}

function buildKoreanSections(theme: Theme, sources: Source[]): string[] {
  const keywordStr = theme.keywords.length > 0 ? theme.keywords.join(", ") : "";
  const desc = theme.description || `${theme.title}에 대한 최신 동향`;

  const titleSection = `# ${theme.title}`;

  const lead = [
    "## 리드문",
    `${desc} ${sources.length}개 출처를 분석해 핵심 내용을 정리했다.` +
      " 이 초안은 AI 평가와 사용자 검토를 거쳐야 최종 승인된다.",
  ].join("\n");

  const background = [
    "## 배경",
    `"${theme.title}"는 최근 주목받는 주제다.` +
      (keywordStr ? ` 이 기사는 ${keywordStr} 등 핵심 키워드를 중심으로 구성했다.` : "") +
      ` 등록된 ${sources.length}개 출처는 이 주제의 다양한 측면을 다루고 있다.`,
  ].join("\n");

  const issueParts = sources.slice(0, 3).map((s) => {
    const point = s.keyPoints?.[0] || s.summary?.substring(0, 80) || "(내용 없음)";
    return `- **${s.title || s.url}**: ${point}`;
  });
  const issues = ["## 핵심 쟁점", ...issueParts].join("\n");

  const comparison = [
    "## 출처 간 비교",
    sources.length >= 2
      ? `${sources.length}개 출처가 공통적으로 다루는 핵심 사안과 각 출처의 관점 차이를 비교했다.` +
        " 출처마다 강조점이 다르며, 이러한 차이는 주제를 다각도로 이해하는 데 도움이 된다."
      : "비교를 위해 최소 2개 이상의 출처가 필요하다.",
  ].join("\n");

  const significance = [
    "## 독자에게 중요한 의미",
    "이 주제는 독자의 일상 또는 업무와 직결될 수 있다." +
      " 출처들이 공통으로 지적하는 변화와 시사점을 주의 깊게 살펴볼 필요가 있다.",
  ].join("\n");

  const outlook = [
    "## 향후 전망 또는 과제",
    `현재까지 확인된 사실을 바탕으로 볼 때 "${theme.title}" 분야는 지속적인 변화가 예상된다.` +
      " 구체적인 전망은 추가 출처와 전문가 검토를 거쳐 보완될 필요가 있다.",
    "",
    "> ⚠️ 이 초안은 mock article generator가 자동 생성한 draft입니다." +
      " AI 평가와 사용자 승인을 거쳐야 reviewed 상태로 전환됩니다.",
  ].join("\n");

  return [titleSection, lead, background, issues, comparison, significance, outlook];
}

function buildEnglishSections(theme: Theme, sources: Source[]): string[] {
  const keywordStr = theme.keywords.length > 0 ? theme.keywords.join(", ") : "";
  const desc = theme.description || `The latest trends in ${theme.title}`;

  const titleSection = `# ${theme.title}`;

  const lead = [
    "## Lead",
    `${desc} This draft synthesizes ${sources.length} registered sources and must pass AI evaluation and human review before publication.`,
  ].join("\n");

  const background = [
    "## Background",
    `"${theme.title}" is a topic that has been gaining attention recently.` +
      (keywordStr ? ` Key topics include: ${keywordStr}.` : "") +
      ` The ${sources.length} registered sources cover various aspects of this subject.`,
  ].join("\n");

  const issueParts = sources.slice(0, 3).map((s) => {
    const point = s.keyPoints?.[0] || s.summary?.substring(0, 80) || "(no content)";
    return `- **${s.title || s.url}**: ${point}`;
  });
  const issues = ["## Key Issues", ...issueParts].join("\n");

  const comparison = [
    "## Comparison Across Sources",
    sources.length >= 2
      ? `Among the ${sources.length} sources, common themes and differing emphases have been identified.` +
        " These differences help illuminate the topic from multiple angles."
      : "At least 2 sources are required for comparison.",
  ].join("\n");

  const significance = [
    "## Why This Matters to Readers",
    "This topic may have direct relevance to readers' daily lives or professional work." +
      " The key changes and implications highlighted by the sources deserve careful attention.",
  ].join("\n");

  const outlook = [
    "## Outlook or Open Questions",
    `Based on what has been confirmed so far, "${theme.title}" is expected to continue evolving.` +
      " Specific forecasts should be supplemented with additional sources and expert review.",
    "",
    "> ⚠️ This draft was auto-generated by the mock article generator." +
      " It must pass AI evaluation and human approval before transitioning to reviewed status.",
  ].join("\n");

  return [titleSection, lead, background, issues, comparison, significance, outlook];
}
