// Phase 1-3: 기사 초안 생성기.
// mock 구현(generateMockArticleDraft)과 실제 AI 연동(generateAiArticleDraft)을 분리한다.
// Phase 1-10: article writer는 source summary(전문) 대신 key_points(불릿 사실)만
// 전달받아 synthesis 없이 paraphrase하는 경향을 차단한다.
// Phase 1-11: tool_use로 JSON 출력을 강제한다.

import { getAnthropicClient, ANTHROPIC_MODEL } from "./anthropic-client";
import type { Source, Theme } from "@/lib/types/domain";
import type { SourceSummary } from "./source-summarizer";

export interface GeneratedArticle {
  title: string;
  content: string;
  citedSourceIds: string[];
}

const MIN_CONTENT_LENGTH = 500;

const FILLER_PARAGRAPH: Record<Theme["language"], string> = {
  ko: "이 기사는 mock article generator에 의해 자동 생성된 초안(draft)입니다. 실제 AI 모델을 통한 생성은 prompts/article-draft.v1.md를 기반으로 연동될 예정이며, 현재는 등록된 출처의 메타데이터를 바탕으로 본문을 구성합니다. 이 초안은 article.contract.yaml의 계약 검사를 통과한 뒤 AI Evals와 사용자 승인 절차를 거쳐야 reviewed 상태로 전환될 수 있습니다.",
  en: "This article is a draft automatically generated by the mock article generator. Generation via a real AI model will be wired up based on prompts/article-draft.v1.md. For now, the body is assembled from the metadata of the registered sources. This draft must pass the article.contract.yaml checks, then AI Evals and human approval before it can be transitioned to the reviewed status.",
};

/**
 * Phase 1-3: 실제 AI API를 호출하지 않는 mock 기사 초안 생성기.
 */
export function generateMockArticleDraft(theme: Theme, sources: Source[]): GeneratedArticle {
  const lang = theme.language;
  const title = theme.title;
  const citedSourceIds = sources.map((source) => source.id);

  const sections =
    lang === "ko"
      ? buildKoreanSections(theme, sources)
      : buildEnglishSections(theme, sources);

  let content = sections.join("\n\n");
  while (content.length < MIN_CONTENT_LENGTH) {
    content += `\n\n${FILLER_PARAGRAPH[lang]}`;
  }

  return { title, content, citedSourceIds };
}

// ─────────────────────────────────────────────────────────────
// AI 기사 생성 (tool_use 방식)
// ─────────────────────────────────────────────────────────────

const ARTICLE_SYSTEM_PROMPT = `당신은 15년 경력의 전문 저널리스트입니다.
복잡한 사안을 일반 독자가 납득할 수 있게 풀어 쓰는 것이 특기이며,
여러 출처를 종합해 하나의 명확한 논지를 가진 기사를 작성합니다.

【작업 순서 — 반드시 이 순서를 지킬 것】
1. synthesis_notes 먼저 작성:
   - 모든 출처의 핵심 사실을 훑은 뒤, 공통 논지와 의미 있는 차이점을 3~5문장으로 정리한다.
   - "이 기사로 독자에게 전달할 가장 중요한 한 가지는 무엇인가?"를 스스로 물어본다.
2. thesis 작성: 위 분석에서 도출한 기사의 핵심 주장을 1~2문장으로 명확히 쓴다.
3. title 작성: thesis를 반영한 제목 (과장·클릭베이트 금지, 40자 이내).
4. content 작성: thesis를 중심으로 7개 섹션 기사를 작성한다.

【문체 기준】
- 한국 주요 일간지 수준의 품격 있는 설명형 저널리즘
- 역피라미드 구조 + 내러티브 흐름
- 각 문단은 하나의 생각을 담고 다음 문단으로 자연스럽게 이어진다
- 결론에 "~일 것이다", "~해야 한다" 식의 빈약한 전망 나열 금지
- 독자가 기사를 다 읽고 나서 "아, 이래서 이 주제가 중요하구나"를 느껴야 한다

【절대 금지】
- key_points 항목을 그대로 인용하거나 단어 순서만 바꾸는 paraphrase 금지
- 각 출처를 순서대로 나열하는 구조 금지 ("A 기사에 따르면... B 기사에 따르면..." 패턴)
- key_points에 없는 수치·날짜·고유명사를 만들어 추가하는 것 금지 (hallucination)
- 500자 미만 본문 금지 (800자 이상 권장)

【7개 섹션 구조】
1. 리드문 — 독자가 계속 읽을 이유를 제시하는 2~3문장 (thesis 반영)
2. 배경 — 이 주제가 왜 지금 중요한지 맥락
3. 핵심 쟁점 — 여러 출처가 공통으로 짚는 문제의 핵심
4. 다각도 분석 — 출처들의 공통점·차이점·긴장관계를 통합해 해석
5. 사실과 데이터 — 출처에 명시된 구체적 사실·수치·사례 (있는 것만)
6. 독자에게 주는 의미 — 이 정보가 일반 독자에게 왜 중요한지 해석
7. 향후 전망 또는 과제 — 출처 근거 있는 전망 또는 아직 해결되지 않은 과제`;

const ARTICLE_TOOL = {
  name: "write_article",
  description: "기사 작성 결과를 저장한다. synthesis_notes → thesis → title → content 순서로 반드시 작성해야 한다.",
  input_schema: {
    type: "object" as const,
    properties: {
      synthesis_notes: {
        type: "string",
        description: "출처 분석 메모 (독자에게 노출되지 않음). 출처들의 공통 논지·차이점·의미를 3~5문장으로 정리.",
      },
      thesis: {
        type: "string",
        description: "이 기사의 핵심 주장 (1~2문장). content 전체가 이 논지를 뒷받침해야 한다.",
      },
      title: {
        type: "string",
        description: "기사 제목 (과장 금지, 40자 이내, thesis를 반영)",
      },
      content: {
        type: "string",
        description: "기사 본문 (markdown, 공백 포함 800자 이상, 7개 섹션 포함)",
      },
      citedSourceIds: {
        type: "array",
        items: { type: "string" },
        description: "본문에서 실제로 활용한 출처 ID 목록 (최소 3개)",
      },
    },
    required: ["synthesis_notes", "thesis", "title", "content", "citedSourceIds"],
  },
};

/**
 * article writer에 보낼 출처 입력을 구성한다.
 * summary 전문 대신 key_points(불릿 사실)만 전달해 paraphrase를 차단한다.
 * key_points가 없는 출처는 summary 앞 150자를 짧게 fallback한다.
 */
function buildSourceBlock(summary: SourceSummary): string {
  const lines = [
    `[출처 ${summary.sourceId}]`,
    `제목: ${summary.title}`,
    `출판사: ${summary.publisher || "(없음)"}`,
    `발행일: ${summary.publishedAt || "(없음)"}`,
  ];

  if (summary.sourceAngle) {
    lines.push(`관점: ${summary.sourceAngle}`);
  }

  if (summary.keyPoints.length > 0) {
    lines.push("핵심 사실:");
    summary.keyPoints.forEach((kp) => lines.push(`  • ${kp}`));
  } else if (summary.summary) {
    // key_points가 없는 구형 출처는 summary 150자로 fallback
    const fallback = summary.summary.length > 150
      ? `${summary.summary.substring(0, 150)}…`
      : summary.summary;
    lines.push(`핵심 내용 (요약): ${fallback}`);
  }

  return lines.join("\n");
}

function buildArticleUserPrompt(theme: Theme, sourceSummaries: SourceSummary[]): string {
  const sourceBlocks = sourceSummaries.map(buildSourceBlock).join("\n\n");

  const audienceNote =
    theme.language === "en" ? "General blog readers" : "일반 블로그 독자 (한국어)";

  return [
    `주제: ${theme.title}`,
    `주제 설명: ${theme.description || "(없음)"}`,
    `주요 키워드: ${theme.keywords.join(", ") || "(없음)"}`,
    `독자 대상: ${audienceNote}`,
    "",
    "─── 출처별 핵심 사실 목록 (요약문이 아닌 사실 추출물) ───",
    sourceBlocks,
    "",
    "─── 작업 지시 ───",
    "위 사실 목록을 바탕으로 write_article 도구를 호출하세요.",
    "반드시 synthesis_notes → thesis → title → content 순서로 채우세요.",
    "각 출처를 순서대로 소개하는 방식으로 작성하지 마세요.",
    "출처의 핵심 사실을 종합·해석하여 하나의 논지가 있는 기사로 작성하세요.",
  ].join("\n");
}

/**
 * Phase 1-4: prompts/article-draft.v1.md 기준으로 Anthropic API를 호출해
 * 기사 초안을 생성한다. tool_use로 JSON 출력을 강제한다.
 * 반환되는 status는 항상 "draft"로 강제한다 (모델 응답값과 무관).
 */
export async function generateAiArticleDraft(
  theme: Theme,
  sourceSummaries: SourceSummary[]
): Promise<GeneratedArticle> {
  const client = getAnthropicClient();

  const response = await client.messages.create({
    model: ANTHROPIC_MODEL,
    max_tokens: 8192,
    system: ARTICLE_SYSTEM_PROMPT,
    tools: [ARTICLE_TOOL],
    tool_choice: { type: "tool", name: "write_article" },
    messages: [{ role: "user", content: buildArticleUserPrompt(theme, sourceSummaries) }],
  });

  const toolUseBlock = response.content.find((block) => block.type === "tool_use");
  if (!toolUseBlock || toolUseBlock.type !== "tool_use") {
    throw new Error("generateAiArticleDraft: AI가 도구를 호출하지 않았습니다.");
  }

  const input = toolUseBlock.input as Record<string, unknown>;

  const title = typeof input.title === "string" ? input.title.trim() : "";
  const content = typeof input.content === "string" ? input.content.trim() : "";

  if (!title || !content) {
    throw new Error("generateAiArticleDraft: AI 응답에 title 또는 content가 없습니다.");
  }

  const citedSourceIds = Array.isArray(input.citedSourceIds)
    ? input.citedSourceIds.filter((id): id is string => typeof id === "string")
    : [];

  return { title, content, citedSourceIds };
}

function buildKoreanSections(theme: Theme, sources: Source[]): string[] {
  const keywordLine =
    theme.keywords.length > 0 ? `주요 키워드: ${theme.keywords.join(", ")}` : "";

  const intro = [
    `# ${theme.title}`,
    "",
    "## 개요",
    theme.description || `${theme.title}에 대한 자동 생성 기사 초안입니다.`,
    keywordLine,
  ]
    .filter(Boolean)
    .join("\n");

  const body = [
    "## 출처별 핵심 내용",
    ...sources.map((source, index) => {
      const meta = [source.publisher, source.publishedAt].filter(Boolean).join(", ");
      return [
        `### ${index + 1}. ${source.title}`,
        source.summary || "(요약 정보가 등록되지 않았습니다.)",
        `- 출처: ${source.url}${meta ? ` (${meta})` : ""}`,
      ].join("\n");
    }),
  ].join("\n\n");

  const conclusion = [
    "## 결론",
    `이상으로 "${theme.title}"에 대해 등록된 ${sources.length}개의 출처를 바탕으로 핵심 내용을 정리했습니다.`,
    "본 초안은 자동 생성된 draft이며, AI 평가와 사용자 검토를 거쳐야 reviewed 상태로 전환됩니다.",
  ].join("\n");

  return [intro, body, conclusion];
}

function buildEnglishSections(theme: Theme, sources: Source[]): string[] {
  const keywordLine =
    theme.keywords.length > 0 ? `Key keywords: ${theme.keywords.join(", ")}` : "";

  const intro = [
    `# ${theme.title}`,
    "",
    "## Overview",
    theme.description || `An automatically generated draft article about ${theme.title}.`,
    keywordLine,
  ]
    .filter(Boolean)
    .join("\n");

  const body = [
    "## Key points by source",
    ...sources.map((source, index) => {
      const meta = [source.publisher, source.publishedAt].filter(Boolean).join(", ");
      return [
        `### ${index + 1}. ${source.title}`,
        source.summary || "(No summary provided.)",
        `- Source: ${source.url}${meta ? ` (${meta})` : ""}`,
      ].join("\n");
    }),
  ].join("\n\n");

  const conclusion = [
    "## Conclusion",
    `This article summarizes ${sources.length} sources registered for "${theme.title}".`,
    "This draft must go through AI evaluation and human review before it can be transitioned to the reviewed status.",
  ].join("\n");

  return [intro, body, conclusion];
}
