// Phase 1: 실제 AI API를 호출하지 않는 mock 기사 초안 생성기.
// prompts/generate-article.prompt.md의 출력 형식(title, content, citedSourceIds)을
// 그대로 따르되, LLM 대신 등록된 출처를 템플릿에 채워 넣는다.
//
// article.contract.yaml의 min-content-length(500자), min-linked-sources(3개) 규칙을
// 항상 만족하도록 생성한다.

import type { Source, Theme } from "@/lib/types/domain";

export interface GeneratedArticle {
  title: string;
  content: string;
  citedSourceIds: string[];
}

const MIN_CONTENT_LENGTH = 500;

const FILLER_PARAGRAPH: Record<Theme["language"], string> = {
  ko: "이 기사는 mock article generator에 의해 자동 생성된 초안(draft)입니다. 실제 AI 모델을 통한 생성은 Phase 2 이후 prompts/generate-article.prompt.md를 기반으로 연동될 예정이며, 현재는 등록된 출처의 메타데이터를 바탕으로 본문을 구성합니다. 이 초안은 article.contract.yaml의 계약 검사를 통과한 뒤 AI Evals와 사용자 승인 절차를 거쳐야 reviewed 상태로 전환될 수 있습니다.",
  en: "This article is a draft automatically generated by the mock article generator. Generation via a real AI model will be wired up in a later phase based on prompts/generate-article.prompt.md. For now, the body is assembled from the metadata of the registered sources. This draft must pass the article.contract.yaml checks, then AI Evals and human approval before it can be transitioned to the reviewed status.",
};

export function generateMockArticle(theme: Theme, sources: Source[]): GeneratedArticle {
  const lang = theme.language;
  const title = theme.title;
  const citedSourceIds = sources.map((source) => source.id);

  const sections =
    lang === "ko"
      ? buildKoreanSections(theme, sources)
      : buildEnglishSections(theme, sources);

  let content = sections.join("\n\n");
  while (content.length < MIN_CONTENT_LENGTH) {
    content += `\n\n${FILLER_PARAGRAPH[lang]}`;
  }

  return { title, content, citedSourceIds };
}

function buildKoreanSections(theme: Theme, sources: Source[]): string[] {
  const keywordLine =
    theme.keywords.length > 0 ? `주요 키워드: ${theme.keywords.join(", ")}` : "";

  const intro = [
    `# ${theme.title}`,
    "",
    "## 개요",
    theme.description || `${theme.title}에 대한 자동 생성 기사 초안입니다.`,
    keywordLine,
  ]
    .filter(Boolean)
    .join("\n");

  const body = [
    "## 출처별 핵심 내용",
    ...sources.map((source, index) => {
      const meta = [source.publisher, source.publishedAt].filter(Boolean).join(", ");
      return [
        `### ${index + 1}. ${source.title}`,
        source.summary || "(요약 정보가 등록되지 않았습니다.)",
        `- 출처: ${source.url}${meta ? ` (${meta})` : ""}`,
      ].join("\n");
    }),
  ].join("\n\n");

  const conclusion = [
    "## 결론",
    `이상으로 "${theme.title}"에 대해 등록된 ${sources.length}개의 출처를 바탕으로 핵심 내용을 정리했습니다.`,
    "본 초안은 자동 생성된 draft이며, AI 평가와 사용자 검토를 거쳐야 reviewed 상태로 전환됩니다.",
  ].join("\n");

  return [intro, body, conclusion];
}

function buildEnglishSections(theme: Theme, sources: Source[]): string[] {
  const keywordLine =
    theme.keywords.length > 0 ? `Key keywords: ${theme.keywords.join(", ")}` : "";

  const intro = [
    `# ${theme.title}`,
    "",
    "## Overview",
    theme.description || `An automatically generated draft article about ${theme.title}.`,
    keywordLine,
  ]
    .filter(Boolean)
    .join("\n");

  const body = [
    "## Key points by source",
    ...sources.map((source, index) => {
      const meta = [source.publisher, source.publishedAt].filter(Boolean).join(", ");
      return [
        `### ${index + 1}. ${source.title}`,
        source.summary || "(No summary provided.)",
        `- Source: ${source.url}${meta ? ` (${meta})` : ""}`,
      ].join("\n");
    }),
  ].join("\n\n");

  const conclusion = [
    "## Conclusion",
    `This article summarizes ${sources.length} sources registered for "${theme.title}".`,
    "This draft must go through AI evaluation and human review before it can be transitioned to the reviewed status.",
  ].join("\n");

  return [intro, body, conclusion];
}
